jobs:
  allow_failures:
    - rust: nightly
  include:
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode9.3
      language: generic
      env:
      - TOXENV=py37
      - PYTHON_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - MACOS_SWIFT_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: osx
      osx_image: xcode10.1
      language: generic
      env:
        - IOS_SWIFT_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: linux
      language: python
      python: 3.7
      # cf https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
      env:
      - TOXENV=py37
      - PYTHON_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: linux
      language: rust
      rust: stable
      env:
        - KOTLIN_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - RUST_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: linux
      language: rust
      rust: beta
      env:
        - RUST_TESTS=true
    - if: env(TRAVIS_BRANCH) = master or branch =~ /^main\/.+$/
      os: linux
      language: rust
      rust: nightly
      env:
        - RUST_TESTS=true

before_install: . ./.travis/before_install.sh

install: ./.travis/install.sh

script: ./.travis/test.sh

git:
  depth: 10
